USE Proyecto3ra
GO

IF OBJECT_ID('SP_VALIDACION_CONSUMO')IS NOT NULL
	DROP PROCEDURE  SP_VALIDACION_CONSUMO
GO

CREATE PROCEDURE SP_VALIDACION_CONSUMO
(
@FK_NUM_MEDIDOR			int


)AS
BEGIN
	SELECT   FK_NUM_MEDIDOR, num_consumo, FK_NUM_TARIFA
		FROM	Consumo
		WHERE FK_NUM_MEDIDOR = @FK_NUM_MEDIDOR;
		END
GO
