USE Proyecto3ra
GO

IF OBJECT_ID('SP_VALIDACION_TARIFA')IS NOT NULL
	DROP PROCEDURE  SP_VALIDACION_TARIFA
GO

CREATE PROCEDURE SP_VALIDACION_TARIFA
(
@FK_NUM_MEDIDOR			int


)AS
BEGIN
	SELECT   FK_NUM_MEDIDOR, periodo_factura, num_tarifa,FK_RFC
		FROM	Tarifa
		WHERE FK_NUM_MEDIDOR = @FK_NUM_MEDIDOR;
		END
GO
